name: C/C++ CI

on:
  push:
    paths-ignore: 
      - 'README.md'
      - 'LICENSE'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make clean
      run: make clean
