name: build-plain-c

on:
  push:
    branches: [ master, main ]
    paths-ignore: 
      - '**/*.md' # To ignore all Markdown files in any directory
      - 'LICENSE'

  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**/*.md' # To ignore all Markdown files in any directory
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: build/hello
    - run: make clean
