name: build-plain-c

on:
  push:
    branches: [ master, main ]
    paths-ignore: 
      - '**/*.md' # To ignore all Markdown files in any directory
      - 'LICENSE'

  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**/*.md' # To ignore all Markdown files in any directory
      - 'LICENSE'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: build/hw
    # - run: grep -q hypervisor /proc/cpuinfo && echo "Virtual Machine" || echo "Bare Metal"
    # - run: ls /sys
    # - run: file -s /sys/class/dmi/id/sys_vendor && cat /sys/class/dmi/id/sys_vendor
    - run: make clean
